MWPW-135095 Add sitemap and query index
adobecom/bacom-blog pull request #17
Opened 2023-10-04 22:37 UTC by Brandon32

* Add Sitemap and update Query Index

Resolves: [MWPW-135095](https://jira.corp.adobe.com/browse/MWPW-135095)

**Test URLs:**
- N/A

2023-10-04 23:05 UTC, meganthecoder requested changes

2023-10-04 23:05 UTC, meganthecoder commented on helix-query.yaml
> +      - '/blog/perspektiven/**'
Why are there French and German folder names included in the US index?

2023-10-04 23:05 UTC, meganthecoder commented on helix-query.yaml
> +      - '/blog/fragments/**'
Don't we want to exclude fragments?

2023-10-04 23:05 UTC, meganthecoder commented on helix-query.yaml
> +      - '/uk/blog/trends/**'
Looks like these should be `/jp/blog/`

2023-10-06 17:07 UTC, Brandon32 commented on helix-query.yaml
> +      - '/blog/perspektiven/**'
Fixed

2023-10-06 17:07 UTC, Brandon32 commented on helix-query.yaml
> +      - '/blog/fragments/**'
Yes, removed

2023-10-06 17:08 UTC, Brandon32 commented on helix-query.yaml
> +      - '/uk/blog/trends/**'
Fixed

2023-10-06 17:31 UTC, meganthecoder approved these changes
Updates look good! Is there already a sitemap-index or are you going to add it later? Also, did you link to the wrong ticket? It goes to the due diligence

2023-10-09 15:56 UTC, JasonHowellSlavin approved these changes

2023-10-09 21:24 UTC, merged